### ISSUE TITLE
PHP WinCache related materials should be updated

### ISSUE THREAD

**Issue by lextm** [MicrosoftDocs/iis-docs#128]
As threads such as https://forums.iis.net/t/1237884.aspx?PHP+WinCahce+extension+fails+to+load+with+PHP+7+2 the WinCache related information on both Docs and IIS.net are out-of-date.

A thorough update is required to avoid confusion.

**Comment by bariscaglar** [comment]
@lextm would you be willing to undertake this task?

**Comment by lextm** [comment]
@bariscaglar though I'd like to, myself is not a PHP developer unfortunately. Thus, I am not quite sure if I can capture all the needed information. I will try to create a pull request in the coming day as an attempt.

**Comment by lextm** [comment]
Created #136 to fix the initial issues.

There are other two pages I would like to update, but have not enough information on how to.

Page 1
-------
https://github.com/MicrosoftDocs/iis-docs/blob/master/iis/application-frameworks/install-and-configure-php-on-iis/use-the-windows-cache-extension-for-php.md

Issues are,

* Still refer to PHP 5.2/5.3. I assume only 5.6.X/7.X.X are supported.
* Still refer to Windows Cache 1.0. I assume only 2.x are supported.
* This article refer to a few Windows operating systems as supported. However, some, llike Windows XP and Windows Server 2003 are end of life now. Such should be removed and new OS should be added.

Page 2
-------
https://www.iis.net/downloads/microsoft/wincache-extension

There are still many reference to this page on IIS.net. However, this page is not up-to-date either, as it misses PHP 7.2 information.

For the above two pages, hope someone from Microsoft can provide guidance.

**Comment by sundarchi1** [comment]
Paging @EricSten-MSFT @ruslany @kjsingla (creators of WinCache) can probably provide guidance.

**Comment by bariscaglar** [comment]
@MicrosoftDocs/iis-contributor for a wide audience.

**Comment by bariscaglar** [comment]
Looks like this should be closed since the fix is merged.

**Comment by surfmuggle** [comment]
Hello @bariscaglar the current version of [use-the-windows-cache-extension-for-php](https://github.com/MicrosoftDocs/iis-docs/blob/master/iis/application-frameworks/install-and-configure-php-on-iis/use-the-windows-cache-extension-for-php.md) does not mention any php 7.* version. The page [iis.net/downloads/microsoft/wincache-extension](https://www.iis.net/downloads/microsoft/wincache-extension) contains php 7.1. But 7.1 is out of support since 22 months. 

So it seems that both pages should be updated again, assuming PHP WinCache works with php 7.2 or 7.3.

**Comment by lextm** [comment]
@surfmuggle You might find some news here which answers your last paragraph,

https://forums.iis.net/t/1242776.aspx?+Pre+Release+WinCache+for+PHP+7+3+and+PHP+7+4alpha1
