### ISSUE TITLE
questions about custom headers

### ISSUE THREAD

**Issue by minoseah629** [MicrosoftDocs/iis-docs#229]
my application uses the custom header section of our web.config. 

```  xml
<system.webServer>
    <httpProtocol>
      <customHeaders>
        <add name="X-Content-Type-Options" value="nosniff"/>
        <add name="X-Frame-Options" value="DENY"/> <!--This header-->
        <add name="X-XSS-Protection" value="1" />
      </customHeaders>
```
But on first user request to the iis website, I get this when I review the network traffic: 

![image](https://user-images.githubusercontent.com/1980068/47679133-dbdd6900-db99-11e8-9655-b06c2bd6b178.png)

I am not sure where this 2nd x frame option header is coming from. 

I review iis site settings and it only had 1 header: 
![image](https://user-images.githubusercontent.com/1980068/47679275-4a222b80-db9a-11e8-8a1e-2692b12aec8b.png)

I review the applicationhost.config and saw same header as the above screenshot
![image](https://user-images.githubusercontent.com/1980068/47679436-a5ecb480-db9a-11e8-8a87-dcf1a5360afe.png)

**Comment by bariscaglar** [comment]
@minoseah629 I don't think the correct place is to pose this question here as this is a location to file issues with the existing or missing documentation. Yours is more of a product support question. I suggest using iis.net forums or Stack Overflow for these kinds of questions in order to get quicker answers. FREB log in this specific case might help identify who sets this particular header in the pipeline.
